CREATE TABLE `slider` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`imagen` VARCHAR(255) NULL DEFAULT NULL,
	`informacion` TEXT NULL DEFAULT NULL,
	`titulo` VARCHAR(100) NULL DEFAULT NULL,
	`subtitulo` VARCHAR(100) NULL DEFAULT NULL,
	`link` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


ALTER TABLE `menu`
	ADD COLUMN `imagen` VARCHAR(255) NULL DEFAULT NULL AFTER `orden`,
	ADD COLUMN `accesoDirecto` INT NULL DEFAULT '0' AFTER `imagen`;
